export enum COLOR_PALLETTE {
  BASE = "#FFF8F2",
  PINK = "#E9686D",
  YELLOW = "#F7C67E",
  LINEAR_PINK = "#FFCFD2",
  LINEAR_YELLOW = "#FFEDCF",
  BLACK = "#333333",
  WHITE = "#FFFFFF",
}

export enum TEXT_COLOR {
  BLACK = "#333333",
  WHITE = "#FFFFFF",
  BROWN = "#8E8682",
}
